# -*- coding: utf-8 -*-
"""Quantum Computing IIT Tirupati.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZaL5u1s7m91-HGok7fzhuWcBgGSts07

<div align="center">

# IIT Tirupati  
## Quantum Computing  
### By Dr. J. Senthil Kumar  

</div>
"""

!pip install qiskit qiskit-aer matplotlib pylatexent --quiet
# Create a circuit with 1 qubit and 1 classical bit
from qiskit import QuantumCircuit
qc = QuantumCircuit(1,1)

# Apply a Madamrd gate to create a superposition: (|0> + |1>))/sqrt(2) - 50%
qc.h(0)

#Measure the qubit
qc.measure(0, 0)

#Draw the circuit
print(qc.draw())

!pip install qiskit matplotlib --quiet

# Create a circuit with 1 qubit and 1 classical bit
from qiskit import QuantumCircuit
qc = QuantumCircuit(1,1)

# Apply a Madamrd gate to create a superposition: (|0> + |1>))/sqrt(2) - 50%
qc.h(0)

#Measure the qubit
qc.measure(0, 0)

#Draw the circuit
print(qc.draw())

qc.x(0)

print(qc.draw())

qc.x(0)
print(qc.draw())

from qiskit import QuantumCircuit
qc = QuantumCircuit(2,2)

# Apply the Hadamard gate to create a superposition:
qc.h(0)
qc.x(0)
qc.x(1)

# Measure the qubit
qc.measure(0,0)

qc.measure(1,0)

# Draw the circuit
qc.draw()

from qiskit import QuantumCircuit

qc = QuantumCircuit(2, 2)

qc.h(0)
qc.x(0)
qc.x(1)

qc.measure(0, 0)
qc.measure(1, 1)

qc.draw()

qc =QuantumCircuit(2,2)  # (2,2) = (q0 , q1 ) = q-bits ; q-bit 1 | q-bit 2
qc.h(0)   # create superposition
qc.cx(0,1) # entangle qubits
qc.measure([0,1],[0,1])
qc.draw()

qc =QuantumCircuit(2,2)  # (2,2) = (q0 , q1 ) = q-bits ; q-bit 1 | q-bit 2
qc.h(0)   # create superposition
qc.cx(0,1) # entangle qubits
qc.measure([0,1],[1,1])
qc.draw()

"""## Deutsch Algorithm Function"""

from qiskit import QuantumCircuit
from qiskt.quantum_info import Statevector

# Deutsch Algorithm Function

def deutsch_algorithm(oracle_fn):
    qc = QuantumCircuit(2,1) # 2qubits, 1 classical bit

    # Step 1: Prepare |0>|1>